# Server Settings
server.port=${PORT:8080}
server.servlet.context-path=/api

# H2 Database Connection details
spring.datasource.url=${DB_URL:jdbc:h2:mem:greetingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:kiran123}

# Hibernate JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Logging
logging.level.root=INFO
logging.level.com.greet=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Custom JWT configuration properties
jwt.secret=${JWT_SECRET:9yB8d5gFhJkMnPrStUvWxYz2b4e6h8kM9yB8d5gFhJkMnPrStUvWxYz2b4e6h8kM}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
